/*
 * FReD
 *
 * FReD - Fog Replicated Data Storage.
 *
 * API version: 0.0.3
 * Contact: tp@mcc.tu-berlin.de
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelError struct {
	Error_ string `json:"error"`
}
