/*
 * FReD
 *
 * FReD - Fog Replicated Data Storage.
 *
 * API version: 0.0.3
 * Contact: tp@mcc.tu-berlin.de
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Seed struct {
	Id   string `json:"id"`
	Addr string `json:"addr"`
}
