/*
 * FReD
 *
 * FReD - Fog Replicated Data Storage.
 *
 * API version: 0.0.4
 * Contact: tp@mcc.tu-berlin.de
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type TriggerListNodes struct {
	Id string `json:"id"`
	Host string `json:"host"`
}
