image: git.tu-berlin.de:5000/mcc-fred/fred/ci:latest

stages:
  - analysis
  - test
  - build
  - release

.dependencies: &dependencies
  - make dep

golint:
  stage: analysis
  before_script: *dependencies
  script:
    - make lint

unit_tests:
  stage: test
  retry: 2
  before_script: *dependencies
  script:
    - make test

race_detector:
  stage: test
  retry: 2
  before_script: *dependencies
  script:
    - make race

code_coverage:
  stage: test
  retry: 2
  before_script: *dependencies
  script:
    - make coverage
  coverage: '/total:\s+\(statements\)\s+\d+.\d*\%/'

build:
  stage: build
  before_script: *dependencies
  script:
    - make

container:
  stage: build
  before_script: *dependencies
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - export IMAGE_TAG=CI_COMMIT_SHORT_SHA-$(echo $CI_COMMIT_REF_NAME | cut -d '/' -f1)
    - docker buildx build --push . -t git.tu-berlin.de:5000/mcc-fred/fred/fred:$IMAGE_TAG
    - docker buildx build --push . -t git.tu-berlin.de:5000/mcc-fred/fred/fredproxy:$IMAGE_TAG
    - docker buildx build --push . -t git.tu-berlin.de:5000/mcc-fred/fred/alexandra:$IMAGE_TAG

release:
  stage: release
  timeout: 20m
  image:
    name: goreleaser/goreleaser
    entrypoint: [""]

  variables:
    DOCKER_REGISTRY: $CI_REGISTRY
    DOCKER_USERNAME: $CI_REGISTRY_USER
    DOCKER_PASSWORD: $CI_REGISTRY_PASSWORD

    # Disable shallow cloning so that goreleaser can diff between tags to
    # generate a changelog.
    GIT_DEPTH: 0

  # Only run this release job for tags, not every commit (for example).
  only:
    refs:
      - tags

  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - goreleaser release --clean
