image: git.tu-berlin.de:5000/mcc-fred/fred/ci:latest

cache:
  paths:
    - .cache

stages:
  - analysis
  - test
  - build
  - 3nodetest
  - release
#  - test_aws

before_script:
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"
  - export CC=clang
  - make dep

golint:
  stage: analysis
  script:
    - make lint

unit_tests:
  stage: test
  script:
    - make test

race_detector:
  stage: test
  script:
    - make race

memory_sanitizer:
  stage: test
  script:
    - make msan

code_coverage:
  stage: test
  script:
    - make coverage

code_coverage_report:
  stage: test
  script:
    - make coverhtml
  only:
    - main

build:
  stage: build
  script:
    - make

container:
  stage: release
  script:
    - make container
    - IFS='/' read -ra components <<< "$CI_COMMIT_REF_NAME"
    - CONTAINER_TAG=${components[0]}
    - if [ "$CI_COMMIT_REF_NAME" == "main" ]; then CONTAINER_TAG=latest; fi;
    - echo $CONTAINER_TAG
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker tag git.tu-berlin.de:5000/mcc-fred/fred/fred git.tu-berlin.de:5000/mcc-fred/fred/fred:$CONTAINER_TAG
    - docker push git.tu-berlin.de:5000/mcc-fred/fred/fred:$CONTAINER_TAG
