image: gitlab-registry.tubit.tu-berlin.de/mcc-fred/fred/ci:latest

cache:
  paths:
    - .cache

stages:
  - test
  - build
  - release

before_script:
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"
  - export CC=clang
  - make dep

unit_tests:
  stage: test
  script:
    - make test

race_detector:
  stage: test
  script:
    - make race

memory_sanitizer:
  stage: test
  script:
    - make msan

code_coverage:
  stage: test
  script:
    - make coverage

code_coverage_report:
  stage: test
  script:
    - make coverhtml
  only:
    - master

lint_code:
  stage: test
  script:
    - make lint

build:
  stage: build
  script:
    - make

container:
  stage: release
  script:
    - make container
    - IFS='/' read -ra components <<< "$CI_COMMIT_REF_NAME"
    - CONTAINER_TAG=${components[0]}
    - if [ "$CI_COMMIT_REF_NAME" == "master" ]; then CONTAINER_TAG=latest; fi;
    - echo $CONTAINER_TAG
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker tag mcc-fred/fred gitlab-registry.tubit.tu-berlin.de/mcc-fred/fred/fred:$CONTAINER_TAG
    - docker push gitlab-registry.tubit.tu-berlin.de/mcc-fred/fred/fred:$CONTAINER_TAG