image: git.tu-berlin.de:5000/mcc-fred/fred/ci:latest

stages:
  - analysis
  - test
  - build
  - release

.dependencies: &dependencies
  - make dep

golint:
  stage: analysis
  before_script:
    *dependencies
  script:
    - make lint

unit_tests:
  stage: test
  before_script:
    *dependencies
  script:
    - make test

race_detector:
  stage: test
  before_script:
    *dependencies
  script:
    - make race

code_coverage:
  stage: test
  before_script:
    *dependencies
  script:
    - make coverage

code_coverage_report:
  stage: test
  before_script:
    *dependencies
  script:
    - make coverhtml
  only:
    - main

build:
  stage: build
  before_script:
    *dependencies
  script:
    - make

release:
  stage: release
  image:
    name: goreleaser/goreleaser
    entrypoint: [ '' ]

  variables:
    DOCKER_REGISTRY: $CI_REGISTRY
    DOCKER_USERNAME: $CI_REGISTRY_USER
    DOCKER_PASSWORD: $CI_REGISTRY_PASSWORD

    # Disable shallow cloning so that goreleaser can diff between tags to
    # generate a changelog.
    GIT_DEPTH: 0

  # Only run this release job for tags, not every commit (for example).
  only:
    refs:
      - tags

  script:
    - goreleaser release --rm-dist