image: gitlab-registry.tubit.tu-berlin.de/mcc-fred/fred/ci:latest

cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

stages:
  - test
  - build

before_script:
  - mkdir -p /go/src/gitlab.tu-berlin.de/mcc-fred /go/src/_/builds
  - cp -r $CI_PROJECT_DIR /go/src/gitlab.tu-berlin.de/mcc-fred/fred
  - ln -s /go/src/gitlab.tu-berlin.de/mcc-fred /go/src/_/builds/mcc-fred
  - export CC=clang-7.0
  - make dep

unit_tests:
  stage: test
  script:
    - make test

race_detector:
  stage: test
  script:
    - make race

memory_sanitizer:
  stage: test
  script:
    - make msan

code_coverage:
  stage: test
  script:
    - make coverage

code_coverage_report:
  stage: test
  script:
    - make coverhtml
  only:
    - master

lint_code:
  stage: test
  script:
    - make lint

build:
  stage: build
  script:
    - make
