image: gitlab-registry.tubit.tu-berlin.de/mcc-fred/fred/ci:latest

cache:
  paths:
    - .cache

stages:
  - test
  - build
  - publish

before_script:
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"
  - export CC=clang
  - make dep

unit_tests:
  stage: test
  script:
    - make test

race_detector:
  stage: test
  script:
    - make race

memory_sanitizer:
  stage: test
  script:
    - make msan

code_coverage:
  stage: test
  script:
    - make coverage

code_coverage_report:
  stage: test
  script:
    - make coverhtml
  only:
    - master

lint_code:
  stage: test
  script:
    - make lint

build:
  stage: build
  script:
    - make

container:
  stage: publish
  script:
    - make container
    - docker push gitlab-registry.tubit.tu-berlin.de/mcc-fred/fred/fred