# FReD Node Configuration File

[location]
# latitude of the server
lat = 52.514927933123914
# longitude of the server
lng = 13.32676300345363

[webserver]
host = ":9001"
ssl = false

[storage]
# adaptor can be either "memory" or "badgerdb" or "remote"
adaptor = "badgerdb"

[zmq]
host = ":5555"

[remotestore]
host = "localhost:1337"

[log]
# debug,info,warn,error,fatal,panic
level = "debug"
# dev: print colored output to stdout
# prod: print json to stdout
handler = "dev"

[nase]
# adress of etcd server
host = "172.26.1.1:2379"